# Build matrix
language: node_js

# cache the node modules
cache:
  directories:
    - node_modules
    - "$HOME/.npm"

# build notification
notifications:
  email:
  - feds@springernature.com
  slack:
    secure: BUpGvVA99nm+6j/ju8WBoHmQ6P3aC2V29zx/RW4uynisjzl4YYCrk3dCYA7gG2OkRHz50+J3d4bqV8kbpUc9XW90n1NjvFoq5SFYrgasp/TLETUVmSfJwgr3D+aEW6xWy7DvzsfIGdw4CHd4Ih35BP3QRxnRgLXlJtOrZ2BH1Wz3xc3yY4v2zMp/B5Fo+pU86QGUIhRSNk70dJYON3iuqH6VJAlkIvIBnUwYCDGWtZQVsfLXwfvZ3nZMWIGAzGIyAtjWrrUY1+RIvZlVInxidA+z19Z3kZrcUaTkAQL73H55ewx7+rftrdWZczM7Tv0G2/rreQuiLYZ+2CLoq0H5uDdXsJxv1LE5xCrrKjMmX7mWGZKQGHUR5IIaBcwmeYeKNbKzrH7yS6b4PVPnp0UegL/j0Oyt2zX8UZRgIPk1CbnpkZF0BgXtEKy40MP3Pq0bwXITecrSRdWMgSwoCEjw7FEUHBh7ts0nSX/3qpf525TtvHAXoWV3kUt9s8ExScVzMXzsA4ph3zHxkgSm0K13Z/xWv384gABJ6rrqnGylqhjpIpXfJG8z0csdccj5E1tFG0kJ12Amepr96K4dqDelzHLuuepnuogdGlnrdfYokS6Rz+J5/1ta/jkpLmtd8e+wjJKk4pjsY0hFObM01gQbHJsTd5ws7ciU7wg++HJkXoo=

# Build script
script:
  - 'npm run lint && npm run test'
